/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Mon Nov 10 21:47:57 2025
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


